### ISSUE TITLE
mobile browser bug

### ISSUE THREAD

**Issue by Zwei-Bier** [sneakytip/dragonsCrownSkillCalculator#1]
The up and down arrows are missing and you cant type any numbers into the number fields.
Tested it in Google Chrome on an android phone.

**Comment by sneakytip** [comment]
I'll take this up with the mobile patch that will be patched after version 1 gets released

**Comment by sneakytip** [comment]
The bug has been addressed as a part of follow-up steps for mobile-ready preparation.
